version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "55 8 * * *"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 10

    labels:
      - "dependencies"
      - "python"

    commit-message:
      prefix: "deps"

    groups:
      python-dependencies:
        patterns:
          - "*"
